name: takhleeq
services:
  product_services:
    build:
      context: ./product_services
      dockerfile: Dockerfile
    volumes:
      - ./product_services:/code # Sync local development directory with the container
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - KAFKA_BOOTSTRAP_SERVER=${AIVEN_KAFKA_BOOTSTRAP_SERVER}
      - AIVEN_KAFKA_USERNAME=${AIVEN_KAFKA_USERNAME}
      - AIVEN_KAFKA_PASSWORD=${AIVEN_KAFKA_PASSWORD}
      - AIVEN_SSL_CA_FILE=${AIVEN_SSL_CA_FILE}
      - KAFKA_PRODUCT_TOPIC=${KAFKA_PRODUCT_TOPIC:-product-topic}
      - KAFKA_CONSUMER_GROUP_ID_FOR_PRODUCT=${KAFKA_CONSUMER_GROUP_ID_FOR_PRODUCT:-product-group}
    ports:
      - "8000:8000" # Expose container port 8000 to host port 8000
    restart: on-failure

  inventory_services:
    build:
      context: ./inventory_services
      dockerfile: Dockerfile
    volumes:
      - ./inventory_services:/code # Sync local development directory with the container
    environment:
      - KAFKA_BOOTSTRAP_SERVER=${AIVEN_KAFKA_BOOTSTRAP_SERVER}
      - AIVEN_KAFKA_USERNAME=${AIVEN_KAFKA_USERNAME}
      - AIVEN_KAFKA_PASSWORD=${AIVEN_KAFKA_PASSWORD}
      - AIVEN_SSL_CA_FILE=${AIVEN_SSL_CA_FILE}
      - KAFKA_INVENTORY_TOPIC=${KAFKA_INVENTORY_TOPIC:-inventory-topic}
      - KAFKA_ORDER_TOPIC=${KAFKA_ORDER_TOPIC:-order-topic}
      - KAFKA_CONSUMER_GROUP_ID_FOR_INVENTORY=${KAFKA_CONSUMER_GROUP_ID_FOR_INVENTORY:-inventory-group}
    ports:
      - "8001:8000" # Expose container port 8000 to host port 8000
    restart: on-failure

  user_services:
    build:
      context: ./user_services
      dockerfile: Dockerfile
    volumes:
      - ./user_services:/code # Sync local development directory with the container
    ports:
      - "8002:8000" # Expose container port 8000 to host port 8000
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - KAFKA_BOOTSTRAP_SERVER=${AIVEN_KAFKA_BOOTSTRAP_SERVER}
      - AIVEN_KAFKA_USERNAME=${AIVEN_KAFKA_USERNAME}
      - AIVEN_KAFKA_PASSWORD=${AIVEN_KAFKA_PASSWORD}
      - AIVEN_SSL_CA_FILE=${AIVEN_SSL_CA_FILE}
      - KAFKA_USER_TOPIC=${KAFKA_USER_TOPIC:-user-topic}
      - KAFKA_CONSUMER_GROUP_ID_FOR_USER=${KAFKA_CONSUMER_GROUP_ID_FOR_USER:-user-group}
      - USER_SERVICE_DATABASE_URL=${USER_SERVICE_DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHMS=${ALGORITHMS:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    restart: on-failure

  order_services:
    build:
      context: ./order_services
      dockerfile: Dockerfile
    volumes:
      - ./order_services:/code # Sync local development directory with the container
    environment:
      - KAFKA_BOOTSTRAP_SERVER=${AIVEN_KAFKA_BOOTSTRAP_SERVER}
      - AIVEN_KAFKA_USERNAME=${AIVEN_KAFKA_USERNAME}
      - AIVEN_KAFKA_PASSWORD=${AIVEN_KAFKA_PASSWORD}
      - AIVEN_SSL_CA_FILE=${AIVEN_SSL_CA_FILE}
      - KAFKA_ORDER_TOPIC=${KAFKA_ORDER_TOPIC:-order-topic}
      - KAFKA_CONSUMER_GROUP_ID_FOR_ORDER=${KAFKA_CONSUMER_GROUP_ID_FOR_ORDER:-order-group}
      - ORDER_SERVICE_DATABASE_URL=${ORDER_SERVICE_DATABASE_URL}
    ports:
      - "8003:8000" # Expose container port 8000 to host port 8000
    restart: on-failure

  notification_services:
    build:
      context: ./notification_services
      dockerfile: Dockerfile
    volumes:
      - ./notification_services:/code
    environment:
      - KAFKA_BOOTSTRAP_SERVER=${AIVEN_KAFKA_BOOTSTRAP_SERVER}
      - AIVEN_KAFKA_USERNAME=${AIVEN_KAFKA_USERNAME}
      - AIVEN_KAFKA_PASSWORD=${AIVEN_KAFKA_PASSWORD}
      - AIVEN_SSL_CA_FILE=${AIVEN_SSL_CA_FILE}
      - KAFKA_ORDER_TOPIC=${KAFKA_ORDER_TOPIC:-order-topic}
      - KAFKA_PAYMENT_TOPIC=${KAFKA_PAYMENT_TOPIC:-payment-topic}
      - KAFKA_USER_TOPIC=${KAFKA_USER_TOPIC:-user-topic}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    ports:
      - "8004:8000"
    restart: on-failure

  payment_services:
    build:
      context: ./payment_services
      dockerfile: Dockerfile
    volumes:
      - ./payment_services:/code
    environment:
      - KAFKA_BOOTSTRAP_SERVER=${AIVEN_KAFKA_BOOTSTRAP_SERVER}
      - AIVEN_KAFKA_USERNAME=${AIVEN_KAFKA_USERNAME}
      - AIVEN_KAFKA_PASSWORD=${AIVEN_KAFKA_PASSWORD}
      - AIVEN_SSL_CA_FILE=${AIVEN_SSL_CA_FILE}
      - KAFKA_PAYMENT_TOPIC=${KAFKA_PAYMENT_TOPIC:-payment-topic}
      - KAFKA_CONSUMER_GROUP_ID_FOR_PAYMENT=${KAFKA_CONSUMER_GROUP_ID_FOR_PAYMENT:-payment-group}
      - PAYMENT_SERVICE_DATABASE_URL=${PAYMENT_SERVICE_DATABASE_URL}
    ports:
      - "8005:8000"
    restart: on-failure

  ai_chatbot:
    build:
      context: ./ai_services/ai_chatbot
      dockerfile: Dockerfile
    volumes:
      - ./ai_services/ai_chatbot:/code
    ports:
      - "8006:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    restart: on-failure

  ai_design_visualization:
    build:
      context: ./ai_services/ai_design_generation_visualization
      dockerfile: Dockerfile
    volumes:
      - ./ai_services/ai_design_generation_visualization:/code
    ports:
      - "8007:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - FLUX_IMAGE_MODEL=${FLUX_IMAGE_MODEL}
      - KAFKA_BOOTSTRAP_SERVER=${AIVEN_KAFKA_BOOTSTRAP_SERVER}
      - AIVEN_KAFKA_USERNAME=${AIVEN_KAFKA_USERNAME}
      - AIVEN_KAFKA_PASSWORD=${AIVEN_KAFKA_PASSWORD}
      - AIVEN_SSL_CA_FILE=${AIVEN_SSL_CA_FILE}
      - KAFKA_DESIGN_TOPIC=${KAFKA_DESIGN_TOPIC:-design-topic}
      - KAFKA_PRODUCT_TOPIC=${KAFKA_PRODUCT_TOPIC:-product-topic}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID_FOR_DESIGN:-ai-design-group}
    restart: on-failure

networks:
  default:
    driver: bridge
    
