FROM python:3.12

LABEL maintainer="HasaanQureshi"

WORKDIR /code

RUN  apt-get update && apt-get install -y\
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY . /code/

# COPY pyproject.toml /code/

RUN poetry config virtualenvs.create false

# RUN poetry lock --no-update

# COPY . /code/

RUN poetry install

EXPOSE 8000

CMD [ "poetry" , "run" , "uvicorn" , "notification_services.main:app" , "--host"  , "0.0.0.0" , "--reload"]